In [75]:
data_dir = 'data/train/'
import glob
a = glob.glob(data_dir + r'/*')
print(a)
sum = 0
for path in a:
    sum += len(glob.glob(path+'/*'))
print(sum)

['data/train/melanoma', 'data/train/nevus', 'data/train/seborrheic_keratosis']
3488


In [76]:
import numpy as np
# read codes and labels from file
import csv

with open('labels_train') as f:
    reader = csv.reader(f, delimiter='\n')
    labels_train = np.array([each for each in reader if len(each) > 0]).squeeze()
with open('codes_train') as f:
    codes_train = np.fromfile(f, dtype=np.float32)
    codes_train = codes_train.reshape((len(labels_train), -1))

In [77]:
codes_train.shape[1]

4096

### 对label单热点编码

In [78]:
from sklearn.preprocessing import LabelBinarizer

lb = LabelBinarizer()
lb.fit(labels_train)

labels_vecs_train = lb.transform(labels_train)

In [86]:
labels_vecs_train[1000:1300]

array([[1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1,

## import random
index = [i for i in range(len(labels_train))] 

random.shuffle(index)
codes_train = codes_train[index]
labels_train= labels_train[index]


### 把打乱的单热点变成数字

In [69]:
train_labels = []
for p in labels_vecs_train:
    p = np.array(p)
    print(p)
    for i,num in p:
        if num == 1:
            break
    print(num)
    train_labels.append(num)
    
   

[1 0 0]
1
[0 1 0]
1
[1 0 0]
1
[0 0 1]
1
[0 1 0]
1
[1 0 0]
1
[1 0 0]
1
[1 0 0]
1
[0 0 1]
1
[1 0 0]
1
[0 1 0]
1
[1 0 0]
1
[1 0 0]
1
[0 1 0]
1
[1 0 0]
1
[0 1 0]
1
[0 0 1]
1
[1 0 0]
1
[0 0 1]
1
[0 0 1]
1
[0 0 1]
1
[0 1 0]
1
[1 0 0]
1
[1 0 0]
1
[0 0 1]
1
[1 0 0]
1
[0 1 0]
1
[1 0 0]
1
[0 0 1]
1
[0 0 1]
1
[0 1 0]
1
[0 1 0]
1
[0 0 1]
1
[0 1 0]
1
[0 1 0]
1
[1 0 0]
1
[0 0 1]
1
[0 1 0]
1
[0 1 0]
1
[1 0 0]
1
[1 0 0]
1
[0 1 0]
1
[1 0 0]
1
[0 1 0]
1
[0 1 0]
1
[0 1 0]
1
[0 1 0]
1
[0 1 0]
1
[1 0 0]
1
[0 1 0]
1
[0 0 1]
1
[1 0 0]
1
[0 1 0]
1
[0 0 1]
1
[0 0 1]
1
[1 0 0]
1
[0 1 0]
1
[1 0 0]
1
[1 0 0]
1
[0 1 0]
1
[0 1 0]
1
[1 0 0]
1
[0 1 0]
1
[0 1 0]
1
[0 0 1]
1
[0 0 1]
1
[1 0 0]
1
[0 0 1]
1
[0 0 1]
1
[1 0 0]
1
[0 1 0]
1
[0 0 1]
1
[1 0 0]
1
[0 0 1]
1
[1 0 0]
1
[1 0 0]
1
[0 1 0]
1
[0 1 0]
1
[0 1 0]
1
[0 0 1]
1
[0 1 0]
1
[1 0 0]
1
[0 1 0]
1
[1 0 0]
1
[0 1 0]
1
[1 0 0]
1
[0 1 0]
1
[0 1 0]
1
[0 0 1]
1
[0 1 0]
1
[1 0 0]
1
[0 0 1]
1
[0 0 1]
1
[0 0 1]
1
[0 1 0]
1
[0 1 0]
1
[0 1 0]
1
[1 0 0]
1
[0 0 1]
1
[0 1 0]
1


In [55]:
train_labels

[1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,


### 对index打乱顺序

In [39]:
import random
index = [i for i in range(len(labels_train))] 

random.shuffle(index)
codes_train = codes_train[index]
labels_train= labels_train[index]


In [42]:
labels_vecs_train

array([[0, 0, 1],
       [1, 0, 0],
       [0, 1, 0],
       ..., 
       [1, 0, 0],
       [0, 0, 1],
       [0, 1, 0]])

In [6]:
import numpy as np
# read codes and labels from file
import csv

with open('labels_valid') as f:
    reader = csv.reader(f, delimiter='\n')
    labels_valid = np.array([each for each in reader if len(each) > 0]).squeeze()
with open('codes_valid') as f:
    codes_valid = np.fromfile(f, dtype=np.float32)
    codes_valid = codes_valid.reshape((len(labels_valid), -1))

In [7]:
len(labels_valid)

150

In [8]:
data_dir = 'data/valid/'
import glob
sum = 0
a = glob.glob(data_dir + '*')
for path in a:
    sum += len(glob.glob(path+'/*'))
print(sum)

150


In [9]:
from sklearn.preprocessing import LabelBinarizer

lb = LabelBinarizer()
lb.fit(labels_valid)

labels_vecs_valid = lb.transform(labels_valid)

In [10]:
import random
index = [i for i in range(len(labels_valid))] 

random.shuffle(index)
codes_valid = codes_valid[index]
labels_valid= labels_valid[index]
labels_vecs_valid = labels_vecs_valid[index]

In [30]:

from keras.models import Sequential
from keras.layers import Dense, Dropout, Activation

model = Sequential()

model.add(Dense(3000,activation='relu',input_dim=codes_train.shape[1]))
model.add(Dropout(0.25))
model.add(Dense(2000,activation='relu'))
model.add(Dropout(0.2))
model.add(Dense(1000,activation='relu'))
model.add(Dropout(0.2))
model.add(Dense(500,activation='relu'))
model.add(Dropout(0.2))
model.add(Dense(labels_vecs_train.shape[1],activation='sigmoid'))

model.compile(optimizer='rmsprop',loss='binary_crossentropy',metrics=['accuracy'])
model.summary()


____________________________________________________________________________________________________
Layer (type)                     Output Shape          Param #     Connected to                     
dense_29 (Dense)                 (None, 3000)          12291000    dense_input_8[0][0]              
____________________________________________________________________________________________________
dropout_19 (Dropout)             (None, 3000)          0           dense_29[0][0]                   
____________________________________________________________________________________________________
dense_30 (Dense)                 (None, 2000)          6002000     dropout_19[0][0]                 
____________________________________________________________________________________________________
dropout_20 (Dropout)             (None, 2000)          0           dense_30[0][0]                   
___________________________________________________________________________________________

In [31]:
def get_batches(x, y, n_batches=10):
    """ Return a generator that yields batches from arrays x and y. """
    batch_size = len(x)//n_batches
    
    for ii in range(0, n_batches*batch_size, batch_size):
        # If we're not on the last batch, grab data with size batch_size
        if ii != (n_batches-1)*batch_size:
            X, Y = x[ii: ii+batch_size], y[ii: ii+batch_size] 
        # On the last batch, grab the rest of the data
        else:
            X, Y = x[ii:], y[ii:]
        # I love generators
        yield X, Y

In [32]:
epochs = 10
model.fit(codes_train,labels_vecs_train,batch_size=20,nb_epoch=epochs,verbose=1,
                validation_data=(codes_valid,labels_vecs_valid))

Train on 3488 samples, validate on 150 samples
Epoch 1/10
3488/3488 [==============================] - 7s - loss: 6.5661 - acc: 0.5903 - val_loss: 5.1297 - val_acc: 0.6800
Epoch 2/10
3488/3488 [==============================] - 7s - loss: 6.4832 - acc: 0.5956 - val_loss: 5.1297 - val_acc: 0.6800
Epoch 3/10
3488/3488 [==============================] - 7s - loss: 6.4832 - acc: 0.5956 - val_loss: 5.1297 - val_acc: 0.6800
Epoch 4/10
3488/3488 [==============================] - 7s - loss: 6.4832 - acc: 0.5956 - val_loss: 5.1297 - val_acc: 0.6800
Epoch 5/10
3488/3488 [==============================] - 7s - loss: 6.4832 - acc: 0.5956 - val_loss: 5.1297 - val_acc: 0.6800
Epoch 6/10
3488/3488 [==============================] - 7s - loss: 6.4832 - acc: 0.5956 - val_loss: 5.1297 - val_acc: 0.6800
Epoch 7/10
3488/3488 [==============================] - 7s - loss: 6.4832 - acc: 0.5956 - val_loss: 5.1297 - val_acc: 0.6800
Epoch 8/10
3488/3488 [==============================] - 7s - loss: 6.4832 - ac

In [16]:
import tensorflow as tf
inputs_ = tf.placeholder(tf.float32, shape=[None, codes_train.shape[1]])
labels_ = tf.placeholder(tf.int64, shape=[None, labels_vecs_train.shape[1]])

fc = tf.layers.dense(inputs_, 256,activation=None)
    
logits = tf.layers.dense(fc, labels_vecs_train.shape[1], activation=None)
cross_entropy = tf.nn.softmax_cross_entropy_with_logits(labels=labels_, logits=logits)
cost = tf.reduce_mean(cross_entropy)

optimizer = tf.train.AdamOptimizer().minimize(cost)

predicted = tf.nn.softmax(logits)
correct_pred = tf.equal(tf.argmax(predicted, 1), tf.argmax(labels_, 1))
accuracy = tf.reduce_mean(tf.cast(correct_pred, tf.float32))

In [ ]:
score = model.evaluate(tensorflow_vgg/score)

In [17]:
import tensorflow as tf
epochs = 10
iteration = 0
saver = tf.train.Saver()
with tf.Session() as sess:
    
    sess.run(tf.global_variables_initializer())
    for e in range(epochs):
        for x, y in get_batches(codes_train, labels_vecs_valid):
            feed = {inputs_: x,
                    labels_: y}
            loss, _ = sess.run([cost, optimizer], feed_dict=feed)
            print("Epoch: {}/{}".format(e+1, epochs),
                  "Iteration: {}".format(iteration),
                  "Training loss: {:.5f}".format(loss))
            iteration += 1
            print("=====")
            if iteration % 5 == 0:
                feed = {inputs_: codes_valid,
                        labels_: labels_vecs_valid}
                val_acc = sess.run(accuracy, feed_dict=feed)
                print("Epoch: {}/{}".format(e, epochs),
                      "Iteration: {}".format(iteration),
                      "Validation Acc: {:.4f}".format(val_acc))
    saver.save(sess, "checkpoints/flowers.ckpt")

InvalidArgumentError: logits and labels must be same size: logits_size=[348,3] labels_size=[150,3]
	 [[Node: SoftmaxCrossEntropyWithLogits_2 = SoftmaxCrossEntropyWithLogits[T=DT_FLOAT, _device="/job:localhost/replica:0/task:0/gpu:0"](Reshape_6, Reshape_7)]]
	 [[Node: Mean_4/_15 = _Recv[client_terminated=false, recv_device="/job:localhost/replica:0/task:0/cpu:0", send_device="/job:localhost/replica:0/task:0/gpu:0", send_device_incarnation=1, tensor_name="edge_136_Mean_4", tensor_type=DT_FLOAT, _device="/job:localhost/replica:0/task:0/cpu:0"]()]]

Caused by op 'SoftmaxCrossEntropyWithLogits_2', defined at:
  File "/home/carnd/anaconda3/envs/dl/lib/python3.5/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/home/carnd/anaconda3/envs/dl/lib/python3.5/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/home/carnd/anaconda3/envs/dl/lib/python3.5/site-packages/ipykernel/__main__.py", line 3, in <module>
    app.launch_new_instance()
  File "/home/carnd/anaconda3/envs/dl/lib/python3.5/site-packages/traitlets/config/application.py", line 658, in launch_instance
    app.start()
  File "/home/carnd/anaconda3/envs/dl/lib/python3.5/site-packages/ipykernel/kernelapp.py", line 474, in start
    ioloop.IOLoop.instance().start()
  File "/home/carnd/anaconda3/envs/dl/lib/python3.5/site-packages/zmq/eventloop/ioloop.py", line 177, in start
    super(ZMQIOLoop, self).start()
  File "/home/carnd/anaconda3/envs/dl/lib/python3.5/site-packages/tornado/ioloop.py", line 887, in start
    handler_func(fd_obj, events)
  File "/home/carnd/anaconda3/envs/dl/lib/python3.5/site-packages/tornado/stack_context.py", line 275, in null_wrapper
    return fn(*args, **kwargs)
  File "/home/carnd/anaconda3/envs/dl/lib/python3.5/site-packages/zmq/eventloop/zmqstream.py", line 440, in _handle_events
    self._handle_recv()
  File "/home/carnd/anaconda3/envs/dl/lib/python3.5/site-packages/zmq/eventloop/zmqstream.py", line 472, in _handle_recv
    self._run_callback(callback, msg)
  File "/home/carnd/anaconda3/envs/dl/lib/python3.5/site-packages/zmq/eventloop/zmqstream.py", line 414, in _run_callback
    callback(*args, **kwargs)
  File "/home/carnd/anaconda3/envs/dl/lib/python3.5/site-packages/tornado/stack_context.py", line 275, in null_wrapper
    return fn(*args, **kwargs)
  File "/home/carnd/anaconda3/envs/dl/lib/python3.5/site-packages/ipykernel/kernelbase.py", line 276, in dispatcher
    return self.dispatch_shell(stream, msg)
  File "/home/carnd/anaconda3/envs/dl/lib/python3.5/site-packages/ipykernel/kernelbase.py", line 228, in dispatch_shell
    handler(stream, idents, msg)
  File "/home/carnd/anaconda3/envs/dl/lib/python3.5/site-packages/ipykernel/kernelbase.py", line 390, in execute_request
    user_expressions, allow_stdin)
  File "/home/carnd/anaconda3/envs/dl/lib/python3.5/site-packages/ipykernel/ipkernel.py", line 196, in do_execute
    res = shell.run_cell(code, store_history=store_history, silent=silent)
  File "/home/carnd/anaconda3/envs/dl/lib/python3.5/site-packages/ipykernel/zmqshell.py", line 501, in run_cell
    return super(ZMQInteractiveShell, self).run_cell(*args, **kwargs)
  File "/home/carnd/anaconda3/envs/dl/lib/python3.5/site-packages/IPython/core/interactiveshell.py", line 2717, in run_cell
    interactivity=interactivity, compiler=compiler, result=result)
  File "/home/carnd/anaconda3/envs/dl/lib/python3.5/site-packages/IPython/core/interactiveshell.py", line 2821, in run_ast_nodes
    if self.run_code(code, result):
  File "/home/carnd/anaconda3/envs/dl/lib/python3.5/site-packages/IPython/core/interactiveshell.py", line 2881, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)
  File "<ipython-input-16-d0590fdc0ac1>", line 8, in <module>
    cross_entropy = tf.nn.softmax_cross_entropy_with_logits(labels=labels_, logits=logits)
  File "/home/carnd/anaconda3/envs/dl/lib/python3.5/site-packages/tensorflow/python/ops/nn_ops.py", line 1617, in softmax_cross_entropy_with_logits
    precise_logits, labels, name=name)
  File "/home/carnd/anaconda3/envs/dl/lib/python3.5/site-packages/tensorflow/python/ops/gen_nn_ops.py", line 2265, in _softmax_cross_entropy_with_logits
    features=features, labels=labels, name=name)
  File "/home/carnd/anaconda3/envs/dl/lib/python3.5/site-packages/tensorflow/python/framework/op_def_library.py", line 763, in apply_op
    op_def=op_def)
  File "/home/carnd/anaconda3/envs/dl/lib/python3.5/site-packages/tensorflow/python/framework/ops.py", line 2395, in create_op
    original_op=self._default_original_op, op_def=op_def)
  File "/home/carnd/anaconda3/envs/dl/lib/python3.5/site-packages/tensorflow/python/framework/ops.py", line 1264, in __init__
    self._traceback = _extract_stack()

InvalidArgumentError (see above for traceback): logits and labels must be same size: logits_size=[348,3] labels_size=[150,3]
	 [[Node: SoftmaxCrossEntropyWithLogits_2 = SoftmaxCrossEntropyWithLogits[T=DT_FLOAT, _device="/job:localhost/replica:0/task:0/gpu:0"](Reshape_6, Reshape_7)]]
	 [[Node: Mean_4/_15 = _Recv[client_terminated=false, recv_device="/job:localhost/replica:0/task:0/cpu:0", send_device="/job:localhost/replica:0/task:0/gpu:0", send_device_incarnation=1, tensor_name="edge_136_Mean_4", tensor_type=DT_FLOAT, _device="/job:localhost/replica:0/task:0/cpu:0"]()]]
